common:
  name: sp2pII-phase4 # name of saving folder
  model: style_based_pix2pixII
  gpu_ids:
  - 0

dataset:
  batch_size: 8
  crop_size: 512
  drop_last: true
  load_size: 512
  preprocess:
  - resize
  unpaired_trainA_folder: "dataset/FFHQ"
  unpaired_trainB_folder: "dataset/AAHQ"
model:
  ngf: 64
testing:
  crop_size: 512
  image_format: png
  load_size: 512
  num_test: 100000
  preprocess:
  - resize
  results_dir: ./results/sp2pII
  visual_names:
  - fake_B
  which_epoch: latest
training:
  beta1: 0.9
  epoch_as_iter: true
  lambda_Feat: 4.0
  lambda_GAN: 1.0
  lambda_L1: 1.0
  lambda_ST: 0.5
  lambda_CLIP: 1.0 # adjustable parameter
  lambda_PROJ: 100.0 # adjustable parameter
  ema: 0.99 # adjustable parameter
  text_prompt: "" # description of reference style
  image_prompt: "" # path to reference style image
  lr: 0.0002 
  lr_policy: linear
  n_epochs: 200 
  n_epochs_decay: 10
  phase: 4
  pretrained_model: pretrained_models/phase3_pretrain_10000.pth
  print_freq: 50
  save_epoch_freq: 200
  style_mixing_prob: 0.5
